---

- name: Set hostname
  hostname: name={{ common_hostname }}

- name: Set timezone to Europe/Ljubljana
  command: "timedatectl set-timezone Europe/Ljubljana"
  register: common_timedate_res
  changed_when: not common_timedate_res.stdout == ""

- name: Configure .bashrc files
  template:
    src: home/bashrc.j2
    dest: "{{ item.dest }}/.bashrc"
    owner: "{{ item.owner }}"
  with_items:
    - { dest: "/root", owner: "root",  ps1: "{{ common_root_ps1 }}" }
    - { dest: "/home/{{ remote_user }}", owner: "{{ remote_user }}", ps1: "{{ common_user_ps1 }}" }
