---

- name: Check that the system has CentOS 7.4+ or RHEL 7.4+ installed
  assert:
    that:
      - ansible_distribution in ["CentOS", "RedHat"]
      - ansible_distribution_version is version_compare('7.4', '>=')

- name: Get remote username
  become: false
  command: whoami
  changed_when: false
  register: common_whoami_res

- name: Save remote username to `remote_user`
  set_fact: remote_user="{{ common_whoami_res.stdout_lines[0] }}"

- include_tasks: sys_packages.yml

- include_tasks: python.yml

- include_tasks: ssh.yml

- include_tasks: security.yml
  when: common_include_security

- include_tasks: awscli.yml
  tags: common_awscli

- include_tasks: config.yml

- include_tasks: guest_additions.yml
  when: common_include_guest_additions
