---

- name: Install Python utilities
  package:
    name:
      - python-virtualenv
      # NOTE: python-ipython-console package provides IPython for running in a
      # terminal and requires far less dependencies than the python-ipython
      # package which provides the full IPython.
      - python-ipython-console
    state: present

- name: Install Python 3.4
  package: name=python34 state=present
  when: common_python3_enabled

- name: Install Python 3.6
  package: name=python36 state=present
  when: common_python36_enabled
