---

- name: Install Python utilities
  package: name={{ item }} state=present
  with_items:
    - python-virtualenv
    # NOTE: python-ipython-console package provides IPython for running in a
    # terminal and requires far less dependencies than the python-ipython
    # package which provides the full IPython.
    - python-ipython-console
