---

- name: Set ~/.ssh directory permissions
  file: path=~/.ssh mode=0700 state=directory
  become: false

- name: "Add admins' public keys to user's authorized_keys file"
  become: false
  authorized_key:
    user: "{{ remote_user }}"
    key: "{{ item }}"
    manage_dir: no
  with_file: common_ssh_authorized_keys

- name: Set authorized_keys file permissions
  file: path=~/.ssh/authorized_keys mode=0600
  become: false

- name: Install fail2ban
  package: name=fail2ban state=present

- name: Ensure fail2ban is enabled and started
  service: name=fail2ban enabled=yes state=started

- name: Allow ssh connections from listed IPs
  firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ item }}/32" service name="ssh" accept'
    state: enabled
    permanent: yes
  with_items: common_ssh_allowed_ips
  when: common_ssh_allowed_ips != []
  notify: Reload firewalld
