---

- name: Reload firewalld
  service: name=firewalld state=reloaded

- name: Restart ssh
  service: name=sshd state=restarted

- name: Restart systemd-journald
  service: name=systemd-journald state=restarted

- name: Restart auditd
  service: name=auditd state=restarted use=service
